version: "3.9"  # optional since v1.27.0
services:
  db:
    image: 'mongo'
    container_name: 'instagram-mongo'
    ports:
     - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=instagram-db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=3)R79ZP,:cv}r_5(
    volumes:
      - mongo-volume:/data/db
volumes:
  mongo-volume: