version: "3.9"
services:
  db:
    image: 'mongo'
    ports:
     - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=instagram-db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=3)R79ZP,:cv}r_5(
    volumes:
      - mongo-volume:/data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    environment: 
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_VHOST: vhost
  gateway:
    image: nginx
    restart: on-failure:10
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/nginx.conf
  gyms-service:
    build: ../../../backend/gym-locations/
    environment:
      - NODE_ENV=docker
      - RABBIT_URL=amqp://user:pass@rabbitmq:5672/vhost
      - DB_URL=mongodb://db:27017
      - DB_USERNAME=admin
      - DB_PASSWORD=3)R79ZP,:cv}r_5(
    depends_on:
      - rabbitmq
    restart: on-failure:5
  visits-service:
    build: ../../../backend/visits-service/
    environment:
      - NODE_ENV=docker
      - RABBIT_URL=amqp://user:pass@rabbitmq:5672/vhost
      - DB_URL=mongodb://db:27017
      - DB_USERNAME=admin
      - DB_PASSWORD=3)R79ZP,:cv}r_5(
    depends_on:
      - rabbitmq
    restart: on-failure:5

volumes:
  mongo-volume:
